server:
  port: 8080

spring:
  application:
    name: cms-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/cms}
    username: ${DB_USERNAME:cms}
    password: ${DB_PASSWORD:cms123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.security: DEBUG
